namespace ScheduleWidget
{
    /// <summary>
    /// Public half of the update signing key (RSA 3072, SHA-256, PKCS#1 v1.5). Generated by tools\New-UpdateKey.ps1;
    /// the private half stays DPAPI-protected on the publishing PC and is never part of the project.
    /// </summary>
    internal static class UpdatePublicKey
    {
        internal const string Xml = "<RSAKeyValue><Modulus>2R+K+WOFKq8oHlm1QiU1+xq5tSMJC3W82LNOdxrt+w9ErWpFC1x1d0iFZQssx73m8+2zaj7VUh70XtiPue+zNUZDctrjwG+7HTNDATuvbiCSPqupIeBCvivL4IUPLVH46cod2M6PKd6eGxegswBFT2MCxCGvMLv+6deYYKNB9vBy1TsEcYPvJ2mM+PGCxczzFlq99Pt7m9tZ1pEwIUf79bIp7zrZ1pPHQ1+39rGa81L0+pptPrxWwnnWAfHwI6L52cJA3gckQlfyA5NkfbzN0AUCgvUH4zbkZYwyvk8NfH4y42P9if7gu7Z91QUKI90dsRBQNZYFa3q9aLI1KG4Wog7Gj5eQQbzokb+SjoMW4UTC/151RCOOLtQLDn/2xgZSh5/DLOHzplj1Sr5WQwaa1AmEEUkSLQ+wDEADe8h7bTeNrAxUp6IjfPYh+KJ2FxHiwK6XKIIegUBTLojJ/VnjhVVGwg9Ng7RQvGSXTEVFf6zb1WFX/SVUxelnT9VDjieR</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>";
    }
}