namespace ScheduleWidget
{
    /// <summary>
    /// Public half of the update signing key (RSA 3072, SHA-256, PKCS#1 v1.5). Generated by tools\New-UpdateKey.ps1;
    /// the private half stays DPAPI-protected on the publishing PC and is never part of the project.
    /// </summary>
    internal static class UpdatePublicKey
    {
        internal const string Xml = "<RSAKeyValue><Modulus>lOxg+Xco86tdPQuUep/8CXQlr86JmKDmXQrZAKyt7e+fVJvnLdS2RPxqgP4g2eNX8yX/y9KzR+XP0nNEpHTyWHkJhlYXxs1qe7BZa0kKKozrSrA9Im0jS0zTSjRzRivGXOTak7EwDIY50POJWha395nv1cU/3F1tooHxb4MUDOulf5WWtE6LOrcPZRuW3Yn5bp5RJ+sd2I8GD0ei7QBoFIEecb2M7eHHmHu9vAAyn34lrcR3YCsKP6TW6TO3TcZQ1QQqhNbH0P6ZUSY5aKSPdyDlPMO8tyIATyHgSSGSKbk9/mhB6afaKXjTiTAD3DwlxEhXaFDUj22H/lSGV3j4wXPr1hGQflU9pCKursQzLbKy5kKUaMNmnZlSWB2xfCpD0+Lw8PutAcH9VcvFIXix4KI/sgcqgv686A1N89hyF9+eHGXCZCDlDIrDu3AdwOWgt7N/U37L51qwND/T4wjvRz35sQzoS0m4EOeutKaYEf4ukJJ+n8OZOIFErNZs4IRF</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>";
    }
}