# Creates the update signing key pair ONCE (RSA 3072).
#  - Private key: %USERPROFILE%\.schedulewidget\update-signing-key.xml, DPAPI-protected (CurrentUser). Never printed.
#  - Public key : written into ScheduleWidget\Services\UpdatePublicKey.cs (embedded in the app; rebuild afterwards).
# If the key already exists it is kept and only the public key source is (re)written; -Force makes a NEW key
# (old installed apps will then reject updates signed with the new key until they are updated by hand).
# Usage: powershell -ExecutionPolicy Bypass -File tools\New-UpdateKey.ps1 [-Force]
param([switch]$Force)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'UpdateSigning.ps1')

$keyPath = Get-UpdatePrivateKeyPath
if ((Test-Path -LiteralPath $keyPath) -and -not $Force) {
    Write-Host "Signing key already exists: $keyPath (kept; use -Force to replace it)."
    $rsa = Read-UpdatePrivateKey $keyPath
} else {
    if (Test-Path -LiteralPath $keyPath) {
        $bak = "$keyPath.old-" + (Get-Date -Format 'yyyyMMdd-HHmmss')
        Move-Item -LiteralPath $keyPath -Destination $bak
        Write-Host "Previous key moved to $bak"
    }
    $rsa = New-Object Security.Cryptography.RSACryptoServiceProvider(3072)
    $rsa.PersistKeyInCsp = $false
    Save-UpdatePrivateKey $rsa $keyPath
    Write-Host "Created new RSA 3072 signing key (DPAPI, CurrentUser): $keyPath"
}

$publicXml = $rsa.ToXmlString($false)
$rsa.Dispose()
$cs = @"
namespace ScheduleWidget
{
    /// <summary>
    /// Public half of the update signing key (RSA 3072, SHA-256, PKCS#1 v1.5). Generated by tools\New-UpdateKey.ps1;
    /// the private half stays DPAPI-protected on the publishing PC and is never part of the project.
    /// </summary>
    internal static class UpdatePublicKey
    {
        internal const string Xml = "$publicXml";
    }
}
"@
$csPath = Get-UpdatePublicKeySourcePath
[IO.File]::WriteAllText($csPath, $cs.Replace("`r`n", "`n").Replace("`n", "`r`n"), (New-Object Text.UTF8Encoding($true)))
Write-Host "Public key written to $csPath"
